[package]
name = "sound-cpal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip8-system = { path = "../chip8-system" }
cpal = "0.15.2"
crossbeam-channel = "0.5.8"
